### ISSUE TITLE
How I can install hpvs cli?

### ISSUE THREAD

**Issue by 1scrooge** [ibm-wsc/hyper-protect-virtual-servers-workshop#13]
Hi.
I installed ibmcloud cli with hpvs plugin, but I can't add new docker registry for the secure build.
![image](https://user-images.githubusercontent.com/32951007/115031968-713b5780-9ed1-11eb-9f74-114c77f628a2.png)

I'm using this tutorial https://ibm-wsc.github.io/hyper-protect-virtual-servers-workshop/securebuild-lab/securebuild-setup/
What I did wrong?

**Comment by silliman** [comment]
Hello Sergey,

this repo has a lab that only works on the on-premises version of Hyper Protect Virtual Servers, which runs in a customer's data center on a Secure Service Container LPAR.   It does not have anything to do with IBM Cloud.

We do have a lab that you can run within the IBM Cloud that does use the ibmcloud CLI as well as the hpvs and ibm container registry plugin.   

It is in draft form but should be workable if you have an IBM Cloud account.  It is in another one of our repos  at https://github.com/ibm-wsc/ibm-cloud-hpvs-sbs-byoi-lab 

It is written for performing the lab in the us-south region but Hyper Protect Virtual Servers is also available in the Frankfurt, Germany region and the Sydney, Australia region, so if one of those is closer to you, you may be able to run the lab there if you make the appropriate substitutions in commands that use us-south or dal13 in command arguments.

This link has more information on available regions for Hyper Protect Virtual Servers: https://cloud.ibm.com/docs/hp-virtual-servers?topic=hp-virtual-servers-faqs#faq3

That lab was also written up as a Jupyter Notebook lab but if you don't have Jupyter Notebook then the main lab, byoi.ipynb should render well enough to follow in GitHub in a browser, at least it does for me.  If it renders poorly for you, go to the very bottom of the lab and it has a link to a tutorial on the IBM Cloud documentation site on which the lab is based.

**Comment by 1scrooge** [comment]
Thank you for the clarification
